spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://49.50.174.34:3306/mabinogi?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: master
    password: alchemy1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate.enable_lazy_load_no_trans: true

server:
  port: 8080

logging:
  level:
    root: info
    discord.bot.mabihelper: debug
    org.hibernate: info

---
spring:
  config:
    activate:
      on-profile: prd
  datasource:
    url: jdbc:mysql://localhost:3306/mabinogi?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: master
    password: alchemy1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        hibernate.enable_lazy_load_no_trans: false

server:
  port: 10000

logging:
  level:
    root: info
    discord.bot.mabihelper: info
    org.hibernate: error
